import { NAME } from './constants';

export const FETCH_POSTS_REQUEST = `${NAME}/FETCH_POSTS_REQUEST`;
export const FETCH_POSTS_SUCCESS = `${NAME}/FETCH_POSTS_SUCCESS`;
export const FETCH_POSTS_FAILURE = `${NAME}/FETCH_POSTS_FAILURE`;
